version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  kittygram:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: vettspace/kittygram_backend
    env_file: .env
    ports:
      - "8080:9000"
    volumes:
      - static:/backend_static
      - media:/app/media
      - ./collected_static:/app/collected_static
    depends_on:
      - kittygram

  frontend:
    image: vettspace/kittygram_frontend
    env_file: .env
    command: cp -r /app/build/. /staticfiles/
    volumes:
      - static:/staticfiles

  gateway:
    image: vettspace/kittygram_gateway
    env_file: .env
    ports:
      - 9000:80
    volumes:
      - static:/staticfiles
      - media:/media
    depends_on:
      - backend
      - frontend