version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  kittygram:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: vettspace/kittygram_backend
    env_file: .env
    ports:
      - "8080:8000"
    volumes:
      - static:/static
      - media:/app/media
  frontend:
    image: vettspace/kittygram_frontend
    env_file: .env
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static
  gateway:
    image: vettspace/kittygram_gateway
    env_file: .env
    ports:
      - 9000:80
    volumes:
      - static:/static
      - media:/media